### ISSUE TITLE
kiwix-serve random url returns 404 in proxy

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-tools#96]
with direct (non-proxied) access to http://192.168.0.37:3000/kiwix/wikipedia_en_medicine_2017-10, the random url
http://192.168.0.37/kiwix/wikipedia_en_medicine_2017-10/A%2fATCvet_code_QS02AA16.html is accessible

however, from the proxy this url returns 404

but 

http://192.168.0.37/kiwix/wikipedia_en_medicine_2017-10/A/ATCvet_code_QS02AA16.html does not return 404 in the proxy

Is it a problem to return '/' instead of %2f for the random url as is done for urls internal to pages?

**Comment by kelson42** [comment]
@swiftugandan An idea?

**Comment by swiftugandan** [comment]
I am running behind an nginx proxy, and am able to load the url, ... a problem with your proxy config perhaps?

**Comment by tim-moody** [comment]
Well, I'm using apache and there are probably a few others who would want to. Substitute can be used to repair such problems but the whole point of this feature is not to have to do so.

The proxy config is dead simple; one line:

ProxyPass /kiwix/  http://127.0.0.1:3000/kiwix/

**Comment by kelson42** [comment]
@swiftugandan Do you have such a kind of configuration for proxy? Maybe you could publish it here?

**Comment by swiftugandan** [comment]
See my nginx config below:

`  
# kiwix
    location ^~ /kiwix/ {
        proxy_pass http://127.0.0.1:3000/kiwix/;
        proxy_redirect     off;
        proxy_pass_header  Server;
        proxy_set_header   Host $http_host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Host $http_host;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;

        error_page 500 502 503 504 /error.html;
    }
`

**Comment by kelson42** [comment]
@tim-moody It sounds quite clear that things are related to the partly urlencoded '/' character. IMO it should not be escaped here. I have trace the problem to the root in the kiwix-lib and propose to fix it with a pull request. Lets hope it will make it.

See https://github.com/kiwix/kiwix-lib/pull/97

**Comment by kelson42** [comment]
@tim-moody As far as I have tested the encoding problem with the "random" feature is fixed now in the kiwix-lib. Please test with the next kiwix-tools which will be generated. Thx for the report and the help of @swiftugandan

**Comment by tim-moody** [comment]
my testing confirms the fix thanks to you and @swiftugandan

**Comment by g000444555** [comment]
I wander why this issue is closed? Reverse proxy still does not work with nginx. I have tried the exact configuration as above. I use nginx version 1.13.9-1 on ubuntu. I think the way to address it, is just like other applications do it, by adding a url_base option to the kiwix-serve command, for example

`kiwix-serve --port=8080 url_base=/kiwix wikipedia.zim`

**Comment by kelson42** [comment]
@g000444555 Which version do you use? Downloaded where?

**Comment by g000444555** [comment]
I use this build: https://ftp.fau.de/kiwix/nightly/2018-03-12/kiwix-tools_armhf-2018-03-12.tar.gz
The application itself seems to work fine, I will actually test it now properly as I have given up the reverse proxy setup.

**Comment by kelson42** [comment]
@g000444555 open a separate bug and share all the details please.
